version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - air-quality-network

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: air_quality
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - air-quality-network

  ingest-service:
    build: ./air-quality-ingest
    container_name: ingest-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - timescaledb
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
      DATABASE_URL: postgres://postgres:password@timescaledb:5432/air_quality?sslmode=disable
    networks:
      - air-quality-network

networks:
  air-quality-network:
    driver: bridge

volumes:
  timescale_data:
